name: Test With Core Bunde
on:
  push:
    branches-ignore: [main]

jobs:
  build-and-test:
    uses: CristiCanizales/bundle-publish-scripts/.github/workflows/validateBundleForDependents.yml@main
    secrets: inherit
